_target_: fdiff.sampling.metrics.MetricCollection
_partial_: true
include_baselines: true
include_specral_density: true
metrics:
  - _target_: fdiff.sampling.metrics.SlicedWasserstein
    _partial_: true
    random_seed: ${random_seed}
    num_directions: 1000
    save_all_distances: true
  - _target_: fdiff.sampling.metrics.MarginalWasserstein
    _partial_: true
    random_seed: ${random_seed}
    save_all_distances: true
