_target_: fdiff.dataloaders.datamodules.ECGDatamodule
data_dir: ${hydra:runtime.cwd}/data
random_seed: ${random_seed}
fourier_transform: ${fourier_transform}
standardize: ${standardize}
batch_size: 64
subsample_localization: false
smooth_frequency: false
