_target_: fdiff.dataloaders.datamodules.MIMICIIIDatamodule
data_dir: ${hydra:runtime.cwd}/data
random_seed: ${random_seed}
fourier_transform: ${fourier_transform}
standardize: ${standardize}
batch_size: 64
n_feats: 40
