_target_: fdiff.dataloaders.datamodules.NASADatamodule
data_dir: ${hydra:runtime.cwd}/data
random_seed: ${random_seed}
fourier_transform: ${fourier_transform}
standardize: ${standardize}
subdataset: charge
batch_size: 16
