- _target_: pytorch_lightning.callbacks.LearningRateMonitor
- _target_: pytorch_lightning.callbacks.ModelCheckpoint
  monitor: val/loss
  filename: "epoch={epoch}-val_loss={val/loss:.2f}"
  auto_insert_metric_name: false
- _target_: pytorch_lightning.callbacks.EarlyStopping
  monitor: val/loss
  patience: 20
- _target_: fdiff.utils.callbacks.SamplingCallback
  every_n_epochs: 10
  sample_batch_size: ${datamodule.batch_size}
  num_samples: 200
  num_diffusion_steps: 1000
  metrics:
    - _target_: fdiff.sampling.metrics.SlicedWasserstein
      _partial_: true
      random_seed: ${random_seed}
      num_directions: 200
    - _target_: fdiff.sampling.metrics.MarginalWasserstein
      _partial_: true
      random_seed: ${random_seed}
