- _target_: pytorch_lightning.callbacks.LearningRateMonitor
- _target_: pytorch_lightning.callbacks.ModelCheckpoint
  monitor: val/loss
  filename: "epoch={epoch}-val_loss={val/loss:.2f}"
  auto_insert_metric_name: false
- _target_: pytorch_lightning.callbacks.EarlyStopping
  monitor: val/loss
  patience: 20
